# Generated by Django 4.0.4 on 2022-05-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityId', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryId', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('UniversityId', models.AutoField(primary_key=True, serialize=False)),
                ('UniversityName', models.CharField(max_length=150)),
                ('CityId_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversitiesAPI.city')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionId', models.AutoField(primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=150)),
                ('CountryId_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversitiesAPI.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='RegionId_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversitiesAPI.region'),
        ),
    ]
