# Generated by Django 4.0.4 on 2022-06-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universities',
            new_name='University',
        ),
    ]
