# Generated by Django 4.0.4 on 2022-06-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesAPI', '0002_rename_universities_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='RegionId_FK',
            new_name='RegionId',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='CountryId_FK',
            new_name='CountryId',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='CityId_FK',
            new_name='CityId',
        ),
    ]
