# Generated by Django 4.0.4 on 2022-06-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesAPI', '0003_rename_regionid_fk_city_regionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='CityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='UniversitiesAPI.city'),
        ),
    ]
