# Generated by Django 4.0.4 on 2022-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesAPI', '0004_alter_university_cityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='UniversityContactInfo',
            field=models.CharField(default='University contact info', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityCoursesLink',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityGeneralDescription',
            field=models.CharField(default='University General Description', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityLogoLink',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityMainPageLink',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
    ]
